"""Risk-form payloads that match ``RiskAssessmentModal`` field names and slider bounds.

Used by eval scripts and accuracy tests. Values are the same strings/ranges the UI sends.
"""
from __future__ import annotations

from typing import Any

# Lifestyle extras the modal appends; models ignore them (payload extra="ignore").
_LIFE = {"activity": "moderate", "smokes": 0}

SAMPLES: dict[str, list[tuple[str, dict[str, Any]]]] = {
    "diabetes": [
        (
            "form_default",
            {
                "pregnancies": 0,
                "glucose": 100,
                "bp": 70,
                "skin": 20,
                "insulin": 80,
                "bmi": 25,
                "pedigree": 0.5,
                "age": 30,
                "gender": 1,
                **_LIFE,
            },
        ),
        (
            "healthy",
            {
                "pregnancies": 1,
                "glucose": 88,
                "bp": 70,
                "skin": 20,
                "insulin": 79,
                "bmi": 22.5,
                "pedigree": 0.2,
                "age": 28,
            },
        ),
        (
            "diseased_pima_like",
            {
                "pregnancies": 7,
                "glucose": 180,
                "bp": 90,
                "skin": 35,
                "insulin": 200,
                "bmi": 38,
                "pedigree": 1.2,
                "age": 52,
            },
        ),
        # Exact slider minima from the diabetes form.
        (
            "all_slider_min",
            {
                "pregnancies": 0,
                "glucose": 50,
                "bp": 40,
                "skin": 7,
                "insulin": 0,
                "bmi": 15,
                "pedigree": 0.08,
                "age": 18,
            },
        ),
        # Exact slider maxima from the diabetes form.
        (
            "all_slider_max",
            {
                "pregnancies": 17,
                "glucose": 200,
                "bp": 120,
                "skin": 99,
                "insulin": 300,
                "bmi": 50,
                "pedigree": 2.5,
                "age": 90,
            },
        ),
        (
            "high_glucose_only",
            {
                "pregnancies": 0,
                "glucose": 200,
                "bp": 70,
                "skin": 20,
                "insulin": 80,
                "bmi": 22,
                "pedigree": 0.2,
                "age": 28,
            },
        ),
        (
            "high_bmi_normal_glucose",
            {
                "pregnancies": 0,
                "glucose": 85,
                "bp": 70,
                "skin": 20,
                "insulin": 80,
                "bmi": 48,
                "pedigree": 0.2,
                "age": 28,
            },
        ),
    ],
    "heart": [
        (
            "form_default",
            {
                "age": 54,
                "sex": "Male",
                "cp": "Asymptomatic (no chest pain)",
                "trestbps": 130,
                "chol": 240,
                "fbs": "No (under 120 mg/dl)",
                "restecg": "Normal",
                "thalach": 150,
                "exang": "No",
                "oldpeak": 1.0,
                "slope": "Flat",
                "ca": 0,
                "thal": "Normal",
            },
        ),
        (
            "healthy",
            {
                "age": 40,
                "sex": "Female",
                "cp": "Typical angina",
                "trestbps": 118,
                "chol": 180,
                "fbs": "No (under 120 mg/dl)",
                "restecg": "Normal",
                "thalach": 175,
                "exang": "No",
                "oldpeak": 0.0,
                "slope": "Upsloping",
                "ca": 0,
                "thal": "Normal",
            },
        ),
        (
            "diseased",
            {
                "age": 68,
                "sex": "Male",
                "cp": "Asymptomatic (no chest pain)",
                "trestbps": 170,
                "chol": 310,
                "fbs": "Yes (over 120 mg/dl)",
                "restecg": "Left ventricular hypertrophy",
                "thalach": 95,
                "exang": "Yes",
                "oldpeak": 3.2,
                "slope": "Downsloping",
                "ca": 3,
                "thal": "Reversible defect",
            },
        ),
        (
            "all_slider_min",
            {
                "age": 18,
                "sex": "Male",
                "cp": "Typical angina",
                "trestbps": 80,
                "chol": 100,
                "fbs": "No (under 120 mg/dl)",
                "restecg": "Normal",
                "thalach": 60,
                "exang": "No",
                "oldpeak": 0.0,
                "slope": "Upsloping",
                "ca": 0,
                "thal": "Normal",
            },
        ),
        (
            "all_slider_max",
            {
                "age": 90,
                "sex": "Male",
                "cp": "Asymptomatic (no chest pain)",
                "trestbps": 200,
                "chol": 600,
                "fbs": "Yes (over 120 mg/dl)",
                "restecg": "Left ventricular hypertrophy",
                "thalach": 220,
                "exang": "Yes",
                "oldpeak": 6.5,
                "slope": "Downsloping",
                "ca": 3,
                "thal": "Reversible defect",
            },
        ),
        (
            "high_thalach_good",
            {
                "age": 54,
                "sex": "Male",
                "cp": "Non-anginal pain",
                "trestbps": 120,
                "chol": 190,
                "fbs": "No (under 120 mg/dl)",
                "restecg": "Normal",
                "thalach": 190,
                "exang": "No",
                "oldpeak": 0.0,
                "slope": "Upsloping",
                "ca": 0,
                "thal": "Normal",
            },
        ),
        (
            "low_thalach_bad",
            {
                "age": 54,
                "sex": "Male",
                "cp": "Non-anginal pain",
                "trestbps": 120,
                "chol": 190,
                "fbs": "No (under 120 mg/dl)",
                "restecg": "Normal",
                "thalach": 80,
                "exang": "No",
                "oldpeak": 0.0,
                "slope": "Upsloping",
                "ca": 0,
                "thal": "Normal",
            },
        ),
        (
            "asymptomatic_cp",
            {
                "age": 54,
                "sex": "Male",
                "cp": "Asymptomatic (no chest pain)",
                "trestbps": 120,
                "chol": 190,
                "fbs": "No (under 120 mg/dl)",
                "restecg": "Normal",
                "thalach": 160,
                "exang": "No",
                "oldpeak": 0.0,
                "slope": "Upsloping",
                "ca": 0,
                "thal": "Normal",
            },
        ),
        (
            "typical_angina_cp",
            {
                "age": 54,
                "sex": "Male",
                "cp": "Typical angina",
                "trestbps": 120,
                "chol": 190,
                "fbs": "No (under 120 mg/dl)",
                "restecg": "Normal",
                "thalach": 160,
                "exang": "No",
                "oldpeak": 0.0,
                "slope": "Upsloping",
                "ca": 0,
                "thal": "Normal",
            },
        ),
    ],
    "liver": [
        (
            "form_default",
            {
                "Age": 45,
                "Gender": "Male",
                "Total_Bilirubin": 1.2,
                "Direct_Bilirubin": 0.4,
                "Alkaline_Phosphotase": 200,
                "Alamine_Aminotransferase": 40,
                "Aspartate_Aminotransferase": 35,
                "Total_Protiens": 6.5,
                "Albumin": 3.5,
                "Albumin_and_Globulin_Ratio": 1.2,
                **_LIFE,
            },
        ),
        (
            "healthy",
            {
                "Age": 35,
                "Gender": "Female",
                "Total_Bilirubin": 0.6,
                "Direct_Bilirubin": 0.2,
                "Alkaline_Phosphotase": 80,
                "Alamine_Aminotransferase": 18,
                "Aspartate_Aminotransferase": 20,
                "Total_Protiens": 7.2,
                "Albumin": 4.4,
                "Albumin_and_Globulin_Ratio": 1.5,
            },
        ),
        (
            "diseased",
            {
                "Age": 58,
                "Gender": "Male",
                "Total_Bilirubin": 8.0,
                "Direct_Bilirubin": 4.5,
                "Alkaline_Phosphotase": 450,
                "Alamine_Aminotransferase": 220,
                "Aspartate_Aminotransferase": 250,
                "Total_Protiens": 5.2,
                "Albumin": 2.1,
                "Albumin_and_Globulin_Ratio": 0.6,
            },
        ),
        (
            "all_slider_min",
            {
                "Age": 1,
                "Gender": "Male",
                "Total_Bilirubin": 0.1,
                "Direct_Bilirubin": 0.1,
                "Alkaline_Phosphotase": 10,
                "Alamine_Aminotransferase": 5,
                "Aspartate_Aminotransferase": 5,
                "Total_Protiens": 2.0,
                "Albumin": 1.0,
                "Albumin_and_Globulin_Ratio": 0.3,
            },
        ),
        (
            "all_slider_max",
            {
                "Age": 100,
                "Gender": "Male",
                "Total_Bilirubin": 25.0,
                "Direct_Bilirubin": 15.0,
                "Alkaline_Phosphotase": 500,
                "Alamine_Aminotransferase": 500,
                "Aspartate_Aminotransferase": 500,
                "Total_Protiens": 9.0,
                "Albumin": 6.0,
                "Albumin_and_Globulin_Ratio": 4.0,
            },
        ),
        (
            "high_albumin_only",
            {
                "Age": 35,
                "Gender": "Female",
                "Total_Bilirubin": 0.6,
                "Direct_Bilirubin": 0.2,
                "Alkaline_Phosphotase": 80,
                "Alamine_Aminotransferase": 18,
                "Aspartate_Aminotransferase": 20,
                "Total_Protiens": 7.2,
                "Albumin": 6.0,
                "Albumin_and_Globulin_Ratio": 1.5,
            },
        ),
        (
            "low_albumin_only",
            {
                "Age": 35,
                "Gender": "Female",
                "Total_Bilirubin": 0.6,
                "Direct_Bilirubin": 0.2,
                "Alkaline_Phosphotase": 80,
                "Alamine_Aminotransferase": 18,
                "Aspartate_Aminotransferase": 20,
                "Total_Protiens": 7.2,
                "Albumin": 1.2,
                "Albumin_and_Globulin_Ratio": 1.5,
            },
        ),
        (
            "high_alt_ast",
            {
                "Age": 35,
                "Gender": "Female",
                "Total_Bilirubin": 0.6,
                "Direct_Bilirubin": 0.2,
                "Alkaline_Phosphotase": 80,
                "Alamine_Aminotransferase": 220,
                "Aspartate_Aminotransferase": 250,
                "Total_Protiens": 7.2,
                "Albumin": 4.4,
                "Albumin_and_Globulin_Ratio": 1.5,
            },
        ),
    ],
    "kidney": [
        (
            "form_default",
            {
                "creatinine": 1.0,
                "urea": 30,
                "hemoglobin": 14,
                "bp": 120,
                "gender": 1,
                **_LIFE,
            },
        ),
        (
            "healthy",
            {"creatinine": 0.8, "urea": 18, "hemoglobin": 14.5, "bp": 118},
        ),
        (
            "diseased",
            {"creatinine": 4.2, "urea": 120, "hemoglobin": 8.5, "bp": 170},
        ),
        # Slider minima: hemoglobin 8 is anemia, so this must NOT score as "low risk".
        (
            "all_slider_min",
            {"creatinine": 0.5, "urea": 10, "hemoglobin": 8.0, "bp": 80},
        ),
        # Slider maxima: hemoglobin 18 is healthier even while creatinine/urea/BP are high.
        (
            "all_slider_max",
            {"creatinine": 5.0, "urea": 200, "hemoglobin": 18.0, "bp": 200},
        ),
        (
            "high_hemoglobin_only",
            {"creatinine": 1.0, "urea": 30, "hemoglobin": 18.0, "bp": 120},
        ),
        (
            "low_hemoglobin_only",
            {"creatinine": 1.0, "urea": 30, "hemoglobin": 8.0, "bp": 120},
        ),
        (
            "high_creatinine_only",
            {"creatinine": 5.0, "urea": 30, "hemoglobin": 14.0, "bp": 120},
        ),
    ],
}


def sample(disease: str, name: str) -> dict[str, Any]:
    for row_name, payload in SAMPLES[disease]:
        if row_name == name:
            return payload
    raise KeyError(f"{disease}/{name}")
