/**
 * Offline RxNorm CUI table for Vitest only. Production resolves names from
 * https://rxnav.nlm.nih.gov/REST (see rxnorm.ts).
 */
export const RXNORM_FIXTURE: Record<string, { rxcui: string; generic: string }> = {
  metformin: { rxcui: "6809", generic: "metformin" },
  glucophage: { rxcui: "6809", generic: "metformin" },
  glycomet: { rxcui: "6809", generic: "metformin" },
  amoxicillin: { rxcui: "723", generic: "amoxicillin" },
  amoxil: { rxcui: "723", generic: "amoxicillin" },
  augmentin: { rxcui: "723", generic: "amoxicillin" },
  warfarin: { rxcui: "11289", generic: "warfarin" },
  coumadin: { rxcui: "11289", generic: "warfarin" },
  ibuprofen: { rxcui: "5640", generic: "ibuprofen" },
  advil: { rxcui: "5640", generic: "ibuprofen" },
  brufen: { rxcui: "5640", generic: "ibuprofen" },
  lisinopril: { rxcui: "29046", generic: "lisinopril" },
  simvastatin: { rxcui: "36567", generic: "simvastatin" },
  zocor: { rxcui: "36567", generic: "simvastatin" },
  acetaminophen: { rxcui: "161", generic: "acetaminophen" },
  tylenol: { rxcui: "161", generic: "acetaminophen" },
  paracetamol: { rxcui: "161", generic: "acetaminophen" },
  dolo: { rxcui: "161", generic: "acetaminophen" },
  crocin: { rxcui: "161", generic: "acetaminophen" },
  calpol: { rxcui: "161", generic: "acetaminophen" },
  aspirin: { rxcui: "1191", generic: "aspirin" },
  ecosprin: { rxcui: "1191", generic: "aspirin" },
  atorvastatin: { rxcui: "83367", generic: "atorvastatin" },
  lipitor: { rxcui: "83367", generic: "atorvastatin" },
  storvas: { rxcui: "83367", generic: "atorvastatin" },
  amlodipine: { rxcui: "17767", generic: "amlodipine" },
  norvasc: { rxcui: "17767", generic: "amlodipine" },
  naproxen: { rxcui: "7258", generic: "naproxen" },
  aleve: { rxcui: "7258", generic: "naproxen" },
  diclofenac: { rxcui: "3355", generic: "diclofenac" },
  voltaren: { rxcui: "3355", generic: "diclofenac" },
  clarithromycin: { rxcui: "21212", generic: "clarithromycin" },
  biaxin: { rxcui: "21212", generic: "clarithromycin" },
  erythromycin: { rxcui: "4053", generic: "erythromycin" },
  ciprofloxacin: { rxcui: "2551", generic: "ciprofloxacin" },
  cipro: { rxcui: "2551", generic: "ciprofloxacin" },
  sildenafil: { rxcui: "136411", generic: "sildenafil" },
  viagra: { rxcui: "136411", generic: "sildenafil" },
  nitroglycerin: { rxcui: "4917", generic: "nitroglycerin" },
  glyceryltrinitrate: { rxcui: "4917", generic: "nitroglycerin" },
  spironolactone: { rxcui: "9997", generic: "spironolactone" },
  aldactone: { rxcui: "9997", generic: "spironolactone" },
  tramadol: { rxcui: "10689", generic: "tramadol" },
  ultram: { rxcui: "10689", generic: "tramadol" },
  sertraline: { rxcui: "36437", generic: "sertraline" },
  zoloft: { rxcui: "36437", generic: "sertraline" },
  fluoxetine: { rxcui: "4493", generic: "fluoxetine" },
  prozac: { rxcui: "4493", generic: "fluoxetine" },
  digoxin: { rxcui: "3407", generic: "digoxin" },
  lanoxin: { rxcui: "3407", generic: "digoxin" },
  amiodarone: { rxcui: "703", generic: "amiodarone" },
  cordarone: { rxcui: "703", generic: "amiodarone" },
  fluconazole: { rxcui: "4450", generic: "fluconazole" },
  diflucan: { rxcui: "4450", generic: "fluconazole" },
  metronidazole: { rxcui: "6922", generic: "metronidazole" },
  flagyl: { rxcui: "6922", generic: "metronidazole" },
  methotrexate: { rxcui: "6851", generic: "methotrexate" },
  trimethoprim: { rxcui: "10829", generic: "trimethoprim" },
  sulfamethoxazole: { rxcui: "10180", generic: "sulfamethoxazole" },
  bactrim: { rxcui: "10831", generic: "sulfamethoxazole / trimethoprim" },
  cotrimoxazole: { rxcui: "10831", generic: "sulfamethoxazole / trimethoprim" },
  theophylline: { rxcui: "10438", generic: "theophylline" },
  potassiumchloride: { rxcui: "8591", generic: "potassium chloride" },
  potassium: { rxcui: "8591", generic: "potassium chloride" },
  losartan: { rxcui: "52175", generic: "losartan" },
  telmisartan: { rxcui: "73494", generic: "telmisartan" },
  telma: { rxcui: "73494", generic: "telmisartan" },
  omeprazole: { rxcui: "7646", generic: "omeprazole" },
  pantoprazole: { rxcui: "40790", generic: "pantoprazole" },
  pantocid: { rxcui: "40790", generic: "pantoprazole" },
  azithromycin: { rxcui: "18631", generic: "azithromycin" },
  azithral: { rxcui: "18631", generic: "azithromycin" },
  cephalexin: { rxcui: "2231", generic: "cephalexin" },
  cefixime: { rxcui: "20489", generic: "cefixime" },
  insulin: { rxcui: "5856", generic: "insulin" },
  glimepiride: { rxcui: "25789", generic: "glimepiride" },
  clopidogrel: { rxcui: "32968", generic: "clopidogrel" },
  plavix: { rxcui: "32968", generic: "clopidogrel" },
  prednisone: { rxcui: "8640", generic: "prednisone" },
  prednisolone: { rxcui: "8638", generic: "prednisolone" },
  levothyroxine: { rxcui: "10582", generic: "levothyroxine" },
  thyronorm: { rxcui: "10582", generic: "levothyroxine" },
  alprazolam: { rxcui: "596", generic: "alprazolam" },
  xanax: { rxcui: "596", generic: "alprazolam" },
  diazepam: { rxcui: "3322", generic: "diazepam" },
  morphine: { rxcui: "7052", generic: "morphine" },
  codeine: { rxcui: "2670", generic: "codeine" },
  penicillin: { rxcui: "7980", generic: "penicillin" },
  ampicillin: { rxcui: "733", generic: "ampicillin" },
};
